(() => {
  'use strict';
  const canvas = document.getElementById('terrain');
  const ctx = canvas.getContext('2d');
  const state = { scenario:null, route:null, start:null, goal:null, risk:4, zoom:1, panX:0, panY:8, dragging:false, pointer:null, pick:null, showElevation:true, showThreat:true, showObstacles:true, simStart:Date.now() };
  const $ = id => document.getElementById(id);
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  async function api(url, options={}) { const response=await fetch(url,options); const body=await response.json(); if(!response.ok) throw new Error(body.error||`Request failed (${response.status})`); return body; }
  function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
  function projection(){const w=canvas.clientWidth,h=canvas.clientHeight,cell=clamp(Math.min(w/48,h/34)*state.zoom,7,28);return {cx:w/2+state.panX,cy:h*.48+state.panY,cell};}
  function point(x,y,z=0){const {cx,cy,cell}=projection();const elev=state.scenario?.layers.elevation[y]?.[x]||95;const height=state.showElevation?(elev-95)*.66:0;return [cx+(x-y)*cell*.5,cy+(x+y)*cell*.25-height-z];}
  function colorFor(x,y){const l=state.scenario.layers,t=l.threat[y][x],e=l.elevation[y][x],norm=clamp((e-78)/40,0,1);let base=state.showElevation?[Math.round(52+norm*38),Math.round(78+norm*48),Math.round(50+norm*27)]:[73,103,67];if(state.showThreat){const a=t*.68;base=base.map((v,i)=>Math.round(v*(1-a)+[206,83,62][i]*a));}return `rgb(${base.join(',')})`;}
  function polygon(points,fill,stroke){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
  function draw(){if(!state.scenario||!ctx)return;const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#17241d';ctx.fillRect(0,0,w,h);
    const {cell}=projection(), W=state.scenario.width,H=state.scenario.height;
    // Draw back-to-front as an isometric heightfield, including exposed side faces.
    for(let sum=0;sum<W+H-1;sum++){for(let y=0;y<H;y++){let x=sum-y;if(x<0||x>=W)continue;const p=point(x,y),q=point(x+1,y),r=point(x+1,y+1),s=point(x,y+1);const t=state.scenario.layers.threat[y][x];polygon([p,q,r,s],colorFor(x,y),'rgba(15,24,18,.33)');
      if(state.showObstacles&&state.scenario.layers.blocked[y][x]){polygon([[p[0],p[1]-cell*.37],[q[0],q[1]-cell*.37],[r[0],r[1]-cell*.37],[s[0],s[1]-cell*.37]],'#867862','#c4ac80');ctx.strokeStyle='#ddc9a0';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p[0],p[1]-cell*.37);ctx.lineTo(r[0],r[1]-cell*.37);ctx.moveTo(q[0],q[1]-cell*.37);ctx.lineTo(s[0],s[1]-cell*.37);ctx.stroke();}
      else if(cell>14 && (x*7+y*11)%19===0){ctx.fillStyle='rgba(209,230,153,.4)';ctx.beginPath();ctx.arc(p[0],p[1]-2,1,0,Math.PI*2);ctx.fill();}
    }}
    if(state.route){ctx.save();ctx.beginPath();state.route.path.forEach(([x,y],i)=>{const p=point(x+.5,y+.5,cell*.38);i?ctx.lineTo(...p):ctx.moveTo(...p)});ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#162019';ctx.lineWidth=7;ctx.stroke();ctx.strokeStyle='#ceef88';ctx.lineWidth=3;ctx.shadowColor='#b9eb76';ctx.shadowBlur=9;ctx.stroke();ctx.restore();}
    marker(state.start,'#b7ed77','A');marker(state.goal,'#ff8c68','B');if(state.scenario.units.length){const u=state.scenario.units[0],p=point(u.x+.5,u.y+.5,cell*.48);ctx.fillStyle='#b9e974';ctx.shadowColor='#aee66c';ctx.shadowBlur=10;ctx.beginPath();ctx.arc(...p,5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#142015';ctx.font='bold 7px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('U',...p);}
  }
  function marker(pos,color,label){if(!pos)return;const p=point(pos.x+.5,pos.y+.5,projection().cell*.45);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(p[0],p[1],7,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#122019';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#142015';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,...p);}
  function updateCoords(){ $('startCoord').textContent=state.start?`GRID ${state.start.x}, ${state.start.y}`:'—';$('goalCoord').textContent=state.goal?`GRID ${state.goal.x}, ${state.goal.y}`:'—'; }
  function showToast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200);}
  function pointerCell(e){const rect=canvas.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top;const {cx,cy,cell}=projection();let best=null,dist=Infinity;for(let y=0;y<state.scenario.height;y++)for(let x=0;x<state.scenario.width;x++){const p=point(x+.5,y+.5);const d=(p[0]-mx)**2+(p[1]-my)**2;if(d<dist){dist=d;best={x,y};}}return dist<Math.max(cell*cell*2,1600)?best:null;}
  async function plan(){const button=$('planButton');button.disabled=true;button.innerHTML='<span>⟳</span> CALCULATING ROUTE…';try{const result=await api('/api/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start:state.start,goal:state.goal,riskWeight:state.risk,slopeWeight:.22})});state.route=result;renderMetrics(result);draw();}catch(e){showToast(e.message);}finally{button.disabled=false;button.innerHTML='<span>⤳</span> PLAN AUTONOMOUS ROUTE <b>↗</b>';}}
  function renderMetrics(r){$('resultTitle').textContent='Autonomous route calculated';$('distanceMetric').innerHTML=`${r.distanceMeters.toLocaleString()} <em>m</em>`;$('exposureMetric').innerHTML=`${r.exposure.toFixed(3)} <em>/ 1.00</em>`;$('nodesMetric').textContent=r.expanded.toLocaleString();const straight=Math.hypot((state.goal.x-state.start.x)*10,(state.goal.y-state.start.y)*10);$('efficiencyMetric').innerHTML=`${straight?Math.min(100,straight/r.distanceMeters*100).toFixed(0):100} <em>%</em>`;$('routeNote').innerHTML=`<span>✓</span> Route ready: <b>${r.path.length} waypoints</b> · weighted cost ${r.cost.toLocaleString()} · mean exposure ${r.exposure.toFixed(3)}.`;$('simTime').textContent=`00:${String(Math.floor((Date.now()-state.simStart)/1000)%60).padStart(2,'0')}`;}
  function setPickMode(which){state.pick=which;showToast(`Click the map to set the ${which} waypoint`);}
  function setup(){
    $('planButton').addEventListener('click',plan);$('pickStart').addEventListener('click',()=>setPickMode('start'));$('pickGoal').addEventListener('click',()=>setPickMode('goal'));
    $('riskSlider').addEventListener('input',e=>{state.risk=Number(e.target.value);$('riskValue').textContent=`${state.risk.toFixed(1)}×`;});
    [['elevationToggle','showElevation'],['threatToggle','showThreat'],['obstacleToggle','showObstacles']].forEach(([id,key])=>$(id).addEventListener('change',e=>{state[key]=e.target.checked;draw();}));
    canvas.addEventListener('pointerdown',e=>{state.dragging=true;state.pointer={x:e.clientX,y:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});
    canvas.addEventListener('pointermove',e=>{if(state.dragging&&state.pointer){const dx=e.clientX-state.pointer.x,dy=e.clientY-state.pointer.y;if(Math.abs(dx)+Math.abs(dy)>3)state.pointer.moved=true;state.panX+=dx;state.panY+=dy;state.pointer={x:e.clientX,y:e.clientY,moved:state.pointer.moved};draw();}else if(state.scenario){const p=pointerCell(e);$('cursorPos').textContent=p?`GRID ${p.x}, ${p.y}`:'GRID —';}});
    canvas.addEventListener('pointerup',e=>{if(!state.pointer)return;const moved=state.pointer.moved;state.dragging=false;state.pointer=null;if(!moved&&state.pick){const p=pointerCell(e);if(p){state[state.pick]=p;state.pick=null;state.route=null;updateCoords();draw();}}});
    canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=clamp(state.zoom*(e.deltaY<0?1.1:.9),.65,2.4);draw();},{passive:false});
    $('zoomIn').addEventListener('click',()=>{state.zoom=clamp(state.zoom*1.15,.65,2.4);draw()});$('zoomOut').addEventListener('click',()=>{state.zoom=clamp(state.zoom/1.15,.65,2.4);draw()});$('resetView').addEventListener('click',()=>{state.zoom=1;state.panX=0;state.panY=8;draw()});
    $('exportGeo').addEventListener('click',async()=>{try{const data=await api('/api/scenario/geojson');const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/geo+json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='north-ridge-training-area.geojson';a.click();URL.revokeObjectURL(a.href);}catch(e){showToast(e.message);}});
    $('menuToggle').addEventListener('click',()=>$('sidebar').classList.toggle('open'));window.addEventListener('resize',resize);
  }
  async function init(){setup();try{state.scenario=await api('/api/scenario');state.start=state.scenario.start;state.goal=state.scenario.goal;$('scenarioName').textContent=state.scenario.name;$('crs').textContent=state.scenario.crs;$('gridMeta').textContent=`${state.scenario.width} × ${state.scenario.height}`;$('resolution').textContent=`${state.scenario.cellSizeMeters} m / cell`; $('unitStatus').textContent=`${state.scenario.units.length} UNIT · READY`;updateCoords();$('loading').classList.add('hidden');resize();setTimeout(plan,250);}catch(e){$('loading').textContent=`Could not load scenario: ${e.message}`;showToast(e.message);}}
  setInterval(()=>{const now=new Date();$('clock').textContent=`${now.toISOString().slice(11,19)} Z`;},1000);init();
})();
